# Generated by Django 5.2.7 on 2025-10-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.CharField(default='349ce7e1-24b7-4936-b940-0ba8c8872c90', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='location',
            table='locations',
        ),
    ]
