# Generated by Django 5.2.7 on 2025-10-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_alter_location_id_alter_location_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.CharField(default='f10cea31-c784-4820-8070-eaafebfa6925', max_length=36, primary_key=True, serialize=False),
        ),
    ]
