# Generated by Django 5.2.7 on 2025-10-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0003_alter_location_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.CharField(default='bf14f9d4-c29a-4802-a2e0-3aa61213b605', max_length=36, primary_key=True, serialize=False),
        ),
    ]
