# Generated by Django 5.2.7 on 2025-10-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0004_alter_location_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.CharField(default='6375aa00-233d-4eb3-ab2c-cbcb53be6a2d', max_length=36, primary_key=True, serialize=False),
        ),
    ]
