# Generated by Django 5.2.7 on 2025-10-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0005_alter_location_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.CharField(default='d7458425-117f-4e13-b1a5-f6986fe9b61f', max_length=36, primary_key=True, serialize=False),
        ),
    ]
