# Generated by Django 5.2.7 on 2025-10-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0006_alter_location_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.CharField(default='4fa63388-120e-4d7f-9b4f-e931e6d32074', max_length=36, primary_key=True, serialize=False),
        ),
    ]
