# Generated by Django 5.2.7 on 2025-10-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0007_alter_location_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.CharField(default='287b4ad3-d9b9-4ffe-aa0f-dc698da70439', max_length=36, primary_key=True, serialize=False),
        ),
    ]
