# Generated by Django 5.2.7 on 2025-10-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0009_alter_location_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.CharField(default='28132a5b-5598-4c72-adfd-a816d0d9bb59', max_length=36, primary_key=True, serialize=False),
        ),
    ]
