# Generated by Django 5.2.7 on 2025-10-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0010_alter_location_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.CharField(default='38964d1b-7c57-4093-b3ad-0adbbd3b4172', max_length=36, primary_key=True, serialize=False),
        ),
    ]
