# Generated by Django 5.2.7 on 2025-10-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0011_alter_location_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.CharField(default='6ca77ef0-eb8c-4601-99a9-fb48c3de0e33', max_length=36, primary_key=True, serialize=False),
        ),
    ]
