# Generated by Django 5.2.7 on 2025-10-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0012_alter_location_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.CharField(default='8e1392cf-f6fb-4166-9b76-5df2e42cea5c', max_length=36, primary_key=True, serialize=False),
        ),
    ]
