# Generated by Django 5.2.7 on 2025-10-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0013_alter_location_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.CharField(default='8e8032c2-aae8-4953-b3ce-f2c50edc6cc7', max_length=36, primary_key=True, serialize=False),
        ),
    ]
