# Generated by Django 5.2.7 on 2025-10-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0014_alter_location_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.CharField(default='ab31f034-f21f-4cce-a27c-a423ccd4f6fc', max_length=36, primary_key=True, serialize=False),
        ),
    ]
