# Generated by Django 5.2.7 on 2025-10-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0015_alter_location_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.CharField(default='09acbb6d-f590-484b-bf5a-9f09baf6003f', max_length=36, primary_key=True, serialize=False),
        ),
    ]
