# Generated by Django 5.2.7 on 2025-10-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0016_alter_location_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.CharField(default='fd40404a-a7a3-4429-be92-e16948019416', max_length=36, primary_key=True, serialize=False),
        ),
    ]
