# Generated by Django 5.2.7 on 2025-10-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0017_alter_location_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.CharField(default='84a7c915-1b03-4ca4-9a19-ff786d178849', max_length=36, primary_key=True, serialize=False),
        ),
    ]
