# Generated by Django 5.2.7 on 2025-10-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0018_alter_location_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.CharField(default='bfded0fa-0a39-405e-84b1-5620bd10883c', max_length=36, primary_key=True, serialize=False),
        ),
    ]
