# Generated by Django 5.2.7 on 2025-10-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0019_alter_location_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.CharField(default='08078cc2-4aa4-4629-aa0c-7899bcb15d5a', max_length=36, primary_key=True, serialize=False),
        ),
    ]
