# Generated by Django 5.2.7 on 2025-10-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0020_alter_location_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.CharField(default='03acc2b5-a119-4184-b153-ed3ae90e1bf7', max_length=36, primary_key=True, serialize=False),
        ),
    ]
