# Generated by Django 5.2.7 on 2025-10-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0021_alter_location_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.CharField(default='ff5d2e2c-0362-450c-9948-8fbc8de0a76a', max_length=36, primary_key=True, serialize=False),
        ),
    ]
