# Generated by Django 5.2.7 on 2025-10-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0022_alter_location_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.CharField(default='8fe34248-7956-4ad4-9e46-e443036164ae', max_length=36, primary_key=True, serialize=False),
        ),
    ]
