# Generated by Django 5.2.7 on 2025-10-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0023_alter_location_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.CharField(default='c5522d87-36d4-4762-b48a-151ff1698feb', max_length=36, primary_key=True, serialize=False),
        ),
    ]
