# Generated by Django 5.2.7 on 2025-10-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0024_alter_location_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.CharField(default='de207129-d3df-423c-a30b-38de792febec', max_length=36, primary_key=True, serialize=False),
        ),
    ]
