# Generated by Django 5.2.7 on 2025-10-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.CharField(default='66f75c28-6877-4c1d-b597-6b46bf6fb307', max_length=36, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('config', models.JSONField()),
            ],
        ),
    ]
