# Generated by Django 5.2.7 on 2025-10-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.CharField(default='abba2510-c502-409d-bf26-909b6e3f964b', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='organization',
            table='organizations',
        ),
    ]
