# Generated by Django 5.2.7 on 2025-10-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_alter_organization_id_alter_organization_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.CharField(default='196f9136-3c3a-4b9a-a8cb-bbade64b5ef3', max_length=36, primary_key=True, serialize=False),
        ),
    ]
