# Generated by Django 5.2.7 on 2025-10-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_alter_organization_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.CharField(default='6732bec4-8daf-49e1-b61a-329397b15788', max_length=36, primary_key=True, serialize=False),
        ),
    ]
