# Generated by Django 5.2.7 on 2025-10-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0004_alter_organization_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.CharField(default='bf3796fc-bc4a-4547-a978-8aa169213538', max_length=36, primary_key=True, serialize=False),
        ),
    ]
