# Generated by Django 5.2.7 on 2025-10-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_alter_organization_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.CharField(default='62e23695-6a58-4afa-99bd-b0456829196b', max_length=36, primary_key=True, serialize=False),
        ),
    ]
