# Generated by Django 5.2.7 on 2025-10-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_alter_organization_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.CharField(default='9b5582ff-7e6c-4bed-8adb-ee34cf5cd2f7', max_length=36, primary_key=True, serialize=False),
        ),
    ]
