# Generated by Django 5.2.7 on 2025-10-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0008_alter_organization_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.CharField(default='8a14d65c-e5c5-4644-954b-c9b610581f62', max_length=36, primary_key=True, serialize=False),
        ),
    ]
