# Generated by Django 5.2.7 on 2025-10-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0009_alter_organization_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.CharField(default='94ba6a7f-bc88-46fb-b927-c5307934fe89', max_length=36, primary_key=True, serialize=False),
        ),
    ]
