# Generated by Django 5.2.7 on 2025-10-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0010_alter_organization_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.CharField(default='28cdc1aa-8f16-4362-bf56-c0d17218525a', max_length=36, primary_key=True, serialize=False),
        ),
    ]
