# Generated by Django 5.2.7 on 2025-10-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0011_alter_organization_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.CharField(default='37acd2eb-f1cc-4ea2-86fb-82acc99e6df0', max_length=36, primary_key=True, serialize=False),
        ),
    ]
