# Generated by Django 5.2.7 on 2025-10-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0012_alter_organization_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.CharField(default='7c4b453a-a9b7-455d-b6b4-ca6b7eb74bee', max_length=36, primary_key=True, serialize=False),
        ),
    ]
