# Generated by Django 5.2.7 on 2025-10-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0013_alter_organization_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.CharField(default='ac196501-b531-40e1-820c-2c3f73104100', max_length=36, primary_key=True, serialize=False),
        ),
    ]
