# Generated by Django 5.2.7 on 2025-10-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0014_alter_organization_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.CharField(default='1f05c894-0b94-4179-ab27-2a2fa86d7cb5', max_length=36, primary_key=True, serialize=False),
        ),
    ]
