# Generated by Django 5.2.7 on 2025-10-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0015_alter_organization_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.CharField(default='a22d573d-8ea3-460e-9d30-51a14eb3a9b1', max_length=36, primary_key=True, serialize=False),
        ),
    ]
