# Generated by Django 5.2.7 on 2025-10-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0016_alter_organization_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.CharField(default='406a048f-a995-4317-ba6d-61f00180f940', max_length=36, primary_key=True, serialize=False),
        ),
    ]
