# Generated by Django 5.2.7 on 2025-10-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0017_alter_organization_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.CharField(default='364ca40c-f325-4d92-a852-9e90b9fa38ad', max_length=36, primary_key=True, serialize=False),
        ),
    ]
