# Generated by Django 5.2.7 on 2025-10-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0018_alter_organization_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.CharField(default='baac2972-c389-4a75-aa75-f059ed0e2c80', max_length=36, primary_key=True, serialize=False),
        ),
    ]
