# Generated by Django 5.2.7 on 2025-10-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0019_alter_organization_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.CharField(default='9bd7e4b9-eec1-48bd-a0be-ba60c3fd05ba', max_length=36, primary_key=True, serialize=False),
        ),
    ]
