# Generated by Django 5.2.7 on 2025-10-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0020_alter_organization_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.CharField(default='88c1bcba-98ab-4ed3-b9bc-d361b571d527', max_length=36, primary_key=True, serialize=False),
        ),
    ]
