# Generated by Django 5.2.7 on 2025-10-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0021_alter_organization_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.CharField(default='c24a5da7-0de1-459f-be68-bff8d5bc677f', max_length=36, primary_key=True, serialize=False),
        ),
    ]
