# Generated by Django 5.2.7 on 2025-10-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0022_alter_organization_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.CharField(default='01921961-88aa-4ab5-b5b4-502fb7b35711', max_length=36, primary_key=True, serialize=False),
        ),
    ]
