# Generated by Django 5.2.7 on 2025-10-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0023_alter_organization_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.CharField(default='3fa35b8b-123f-4656-bc0c-37b5edf84635', max_length=36, primary_key=True, serialize=False),
        ),
    ]
