# Generated by Django 5.2.7 on 2025-10-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0024_alter_organization_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='id',
            field=models.CharField(default='f3e32f82-9cf1-49c2-83f9-4e7cfb62351c', max_length=36, primary_key=True, serialize=False),
        ),
    ]
