# Generated by Django 5.2.7 on 2025-10-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default='227f3a2b-5140-42c6-b111-c236602bc941', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='employee',
            table='employees',
        ),
    ]
