# Generated by Django 5.2.7 on 2025-10-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0002_alter_employee_id_alter_employee_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default='7d8f4290-d1e1-4389-a1fb-06edefcdd5aa', max_length=36, primary_key=True, serialize=False),
        ),
    ]
