# Generated by Django 5.2.7 on 2025-10-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0003_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default='da1d7ab8-eab3-4a2b-8f25-4442c656b065', max_length=36, primary_key=True, serialize=False),
        ),
    ]
