# Generated by Django 5.2.7 on 2025-10-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0004_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default='cbc5d350-7343-4ac1-add0-15ef4a7c6151', max_length=36, primary_key=True, serialize=False),
        ),
    ]
