# Generated by Django 5.2.7 on 2025-10-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0005_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default='f59f4526-cd72-4eb0-9414-c0998a6a2493', max_length=36, primary_key=True, serialize=False),
        ),
    ]
