# Generated by Django 5.2.7 on 2025-10-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0006_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default='c1b06e14-6e93-4a49-a309-2c62c45b7b51', max_length=36, primary_key=True, serialize=False),
        ),
    ]
