# Generated by Django 5.2.7 on 2025-10-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0007_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default='042478bc-d14e-4e04-ad6e-0c0fdd0f83d6', max_length=36, primary_key=True, serialize=False),
        ),
    ]
