# Generated by Django 5.2.7 on 2025-10-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0008_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default='be2add53-2341-4726-8659-9e75805f48bb', max_length=36, primary_key=True, serialize=False),
        ),
    ]
