# Generated by Django 5.2.7 on 2025-10-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0010_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default='a0b41554-37d0-4848-8936-9f1f64d9cab3', max_length=36, primary_key=True, serialize=False),
        ),
    ]
