# Generated by Django 5.2.7 on 2025-10-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0011_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default='6c237ef6-cbef-4386-a12e-f8ae644078f5', max_length=36, primary_key=True, serialize=False),
        ),
    ]
