# Generated by Django 5.2.7 on 2025-10-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0012_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default='dc69957b-14d9-4f3e-b73b-ecacafc09f14', max_length=36, primary_key=True, serialize=False),
        ),
    ]
