# Generated by Django 5.2.7 on 2025-10-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0013_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default='7251b7e8-2e12-4dfe-aaff-754fefea1397', max_length=36, primary_key=True, serialize=False),
        ),
    ]
