# Generated by Django 5.2.7 on 2025-10-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0015_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default='33d39058-ed40-4dda-b626-0ecaca64064a', max_length=36, primary_key=True, serialize=False),
        ),
    ]
