# Generated by Django 5.2.7 on 2025-10-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0016_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default='0ee94f2e-c284-46d4-9dab-652cad74d187', max_length=36, primary_key=True, serialize=False),
        ),
    ]
