# Generated by Django 5.2.7 on 2025-10-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0017_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default='e66372db-7ace-4700-bee7-4ecbd9dbf0d8', max_length=36, primary_key=True, serialize=False),
        ),
    ]
