# Generated by Django 5.2.7 on 2025-10-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0019_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default='c1bfac95-d1fc-4f8e-b05a-f7155233a2e7', max_length=36, primary_key=True, serialize=False),
        ),
    ]
