# Generated by Django 5.2.7 on 2025-10-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0020_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default='c062d9e7-dbdd-4f6a-adf1-06f63cf6e343', max_length=36, primary_key=True, serialize=False),
        ),
    ]
