# Generated by Django 5.2.7 on 2025-10-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0021_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default='acb7dd81-37ad-4197-9925-9281c6508151', max_length=36, primary_key=True, serialize=False),
        ),
    ]
