# Generated by Django 5.2.7 on 2025-10-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0022_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default='cda9fce1-6589-4ea0-9329-8834754ede70', max_length=36, primary_key=True, serialize=False),
        ),
    ]
