# Generated by Django 5.2.7 on 2025-10-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0023_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default='3ebc2efe-f470-4f4b-b374-3704a76ca92f', max_length=36, primary_key=True, serialize=False),
        ),
    ]
