# Generated by Django 5.2.7 on 2025-10-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employee', '0024_alter_employee_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='id',
            field=models.CharField(default='be188d39-2d8d-44be-ad06-159254221975', max_length=36, primary_key=True, serialize=False),
        ),
    ]
