# Generated by Django 5.2.7 on 2025-10-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.CharField(default='8b1c6b56-feb7-4e0f-8518-bc3c615399d8', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='position',
            table='positions',
        ),
    ]
