# Generated by Django 5.2.7 on 2025-10-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0002_alter_position_id_alter_position_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.CharField(default='a63c57b4-e6d7-4392-b433-27abc38b1121', max_length=36, primary_key=True, serialize=False),
        ),
    ]
