# Generated by Django 5.2.7 on 2025-10-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0003_alter_position_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.CharField(default='bbdecc8a-8c67-4e38-a589-526d883810a9', max_length=36, primary_key=True, serialize=False),
        ),
    ]
