# Generated by Django 5.2.7 on 2025-10-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0004_alter_position_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.CharField(default='71c08d4d-c1ed-455b-86cc-070373fbbc57', max_length=36, primary_key=True, serialize=False),
        ),
    ]
