# Generated by Django 5.2.7 on 2025-10-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0005_alter_position_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.CharField(default='3d7901e5-7d32-446d-8368-a851119660b9', max_length=36, primary_key=True, serialize=False),
        ),
    ]
