# Generated by Django 5.2.7 on 2025-10-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0006_alter_position_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.CharField(default='fa6ddd06-db93-4e39-9528-03533563bad0', max_length=36, primary_key=True, serialize=False),
        ),
    ]
