# Generated by Django 5.2.7 on 2025-10-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0007_alter_position_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.CharField(default='4a522c6f-bbcb-411c-be36-9bdaaff66a36', max_length=36, primary_key=True, serialize=False),
        ),
    ]
