# Generated by Django 5.2.7 on 2025-10-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0008_alter_position_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.CharField(default='20a8b453-b68e-4b7c-8616-21a4a57eda8c', max_length=36, primary_key=True, serialize=False),
        ),
    ]
