# Generated by Django 5.2.7 on 2025-10-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0009_alter_position_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.CharField(default='f4a5f9cf-3fb2-4ed7-b921-6d86e747fc9f', max_length=36, primary_key=True, serialize=False),
        ),
    ]
