# Generated by Django 5.2.7 on 2025-10-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0010_alter_position_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.CharField(default='621699cf-238e-4bf0-baaa-3a905050a04f', max_length=36, primary_key=True, serialize=False),
        ),
    ]
