# Generated by Django 5.2.7 on 2025-10-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0011_alter_position_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.CharField(default='44dc9462-ced0-48dc-ba5a-4bcd77c0071c', max_length=36, primary_key=True, serialize=False),
        ),
    ]
