# Generated by Django 5.2.7 on 2025-10-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0012_alter_position_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.CharField(default='f7de2f7a-0e89-46ad-a79e-8b12f072c24c', max_length=36, primary_key=True, serialize=False),
        ),
    ]
