# Generated by Django 5.2.7 on 2025-10-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0014_alter_position_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.CharField(default='fd26cc79-945e-4e4e-aa0a-3bff8434667b', max_length=36, primary_key=True, serialize=False),
        ),
    ]
