# Generated by Django 5.2.7 on 2025-10-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0015_alter_position_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.CharField(default='0897d17c-d3a8-43f6-b470-7afb5e17c2af', max_length=36, primary_key=True, serialize=False),
        ),
    ]
