# Generated by Django 5.2.7 on 2025-10-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0016_alter_position_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.CharField(default='aebc415e-b190-4d5f-974c-acb3ef32865d', max_length=36, primary_key=True, serialize=False),
        ),
    ]
