# Generated by Django 5.2.7 on 2025-10-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0017_alter_position_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.CharField(default='61001751-b691-4b57-b413-d4b9437c8554', max_length=36, primary_key=True, serialize=False),
        ),
    ]
