# Generated by Django 5.2.7 on 2025-10-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0018_alter_position_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.CharField(default='aa3ec24b-fcfe-4ea2-9ba5-fa4d9485ea88', max_length=36, primary_key=True, serialize=False),
        ),
    ]
