# Generated by Django 5.2.7 on 2025-10-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0019_alter_position_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.CharField(default='0e83eae0-d59a-443f-af40-7cddc6d19b71', max_length=36, primary_key=True, serialize=False),
        ),
    ]
