# Generated by Django 5.2.7 on 2025-10-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0020_alter_position_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.CharField(default='d669e180-3ded-49d4-acd9-f530c92e5cf5', max_length=36, primary_key=True, serialize=False),
        ),
    ]
