# Generated by Django 5.2.7 on 2025-10-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0021_alter_position_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.CharField(default='3ef38188-3e65-4119-9469-e17a98c2a8ba', max_length=36, primary_key=True, serialize=False),
        ),
    ]
