# Generated by Django 5.2.7 on 2025-10-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0022_alter_position_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.CharField(default='07cf274e-556e-44fe-b6e7-751d974b630b', max_length=36, primary_key=True, serialize=False),
        ),
    ]
