# Generated by Django 5.2.7 on 2025-10-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0023_alter_position_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.CharField(default='c0ba1a67-1653-4fa5-ae55-14930fa6c306', max_length=36, primary_key=True, serialize=False),
        ),
    ]
