# Generated by Django 5.2.7 on 2025-10-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position', '0024_alter_position_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='position',
            name='id',
            field=models.CharField(default='629354cf-ba1b-4c43-9c75-1b4e1c11b5d8', max_length=36, primary_key=True, serialize=False),
        ),
    ]
