# Generated by Django 5.2.7 on 2025-10-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.CharField(default='f9ea7418-812e-481a-b6fe-b06923771019', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='userprofile',
            table='users',
        ),
    ]
