# Generated by Django 5.2.7 on 2025-10-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_alter_userprofile_id_alter_userprofile_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.CharField(default='24eabdf3-4b6b-40e8-acc6-b15b7ad48110', max_length=36, primary_key=True, serialize=False),
        ),
    ]
