# Generated by Django 5.2.7 on 2025-10-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_userprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.CharField(default='45cdea55-69f0-4ee3-86aa-ecbc02cf98b8', max_length=36, primary_key=True, serialize=False),
        ),
    ]
