# Generated by Django 5.2.7 on 2025-10-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_userprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.CharField(default='42cbe4da-b5c0-404e-84f4-7f8bbfe49707', max_length=36, primary_key=True, serialize=False),
        ),
    ]
