# Generated by Django 5.2.7 on 2025-10-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_userprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.CharField(default='a99b70b2-c95f-4d09-9296-d174a4d9447b', max_length=36, primary_key=True, serialize=False),
        ),
    ]
