# Generated by Django 5.2.7 on 2025-10-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_userprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.CharField(default='38d7947d-97dc-4307-87d3-92f8da88305a', max_length=36, primary_key=True, serialize=False),
        ),
    ]
