# Generated by Django 5.2.7 on 2025-10-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_alter_userprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.CharField(default='bb94c5b1-cbf4-4312-b66a-496ca38233de', max_length=36, primary_key=True, serialize=False),
        ),
    ]
