# Generated by Django 5.2.7 on 2025-10-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_userprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.CharField(default='07e194eb-8c2c-4b08-aaf2-5373f18c96a5', max_length=36, primary_key=True, serialize=False),
        ),
    ]
