# Generated by Django 5.2.7 on 2025-10-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_userprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.CharField(default='00d31404-37cd-42eb-9890-cd7e93fa1284', max_length=36, primary_key=True, serialize=False),
        ),
    ]
