# Generated by Django 5.2.7 on 2025-10-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_userprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.CharField(default='eb2fa229-78c2-4489-9bc4-749cd64b65a7', max_length=36, primary_key=True, serialize=False),
        ),
    ]
