# Generated by Django 5.2.7 on 2025-10-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_userprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.CharField(default='43cdefc2-95dc-4616-8a8d-a0a9ff9e2696', max_length=36, primary_key=True, serialize=False),
        ),
    ]
