# Generated by Django 5.2.7 on 2025-10-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_userprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.CharField(default='e4e9cc2a-29dd-432a-be4c-7a2595c8b341', max_length=36, primary_key=True, serialize=False),
        ),
    ]
