# Generated by Django 5.2.7 on 2025-10-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_userprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.CharField(default='7b70b0a9-32b8-4704-863c-d595c3c1465e', max_length=36, primary_key=True, serialize=False),
        ),
    ]
