# Generated by Django 5.2.7 on 2025-10-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_userprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.CharField(default='a4f3399d-cca9-45f5-950f-6f0f1ddfdfe3', max_length=36, primary_key=True, serialize=False),
        ),
    ]
