# Generated by Django 5.2.7 on 2025-10-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_alter_userprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.CharField(default='0a55b774-a4f4-496f-950c-d703fe206b69', max_length=36, primary_key=True, serialize=False),
        ),
    ]
