# Generated by Django 5.2.7 on 2025-10-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_userprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.CharField(default='c994c6ea-5f9c-4dd5-b897-a2416ab46e44', max_length=36, primary_key=True, serialize=False),
        ),
    ]
