# Generated by Django 5.2.7 on 2025-10-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_alter_userprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.CharField(default='5f96df76-06ac-42df-805c-f9724cfe27e9', max_length=36, primary_key=True, serialize=False),
        ),
    ]
