# Generated by Django 5.2.7 on 2025-10-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_alter_userprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.CharField(default='522b018f-dfd1-45da-aabe-f191657ea85f', max_length=36, primary_key=True, serialize=False),
        ),
    ]
