# Generated by Django 5.2.7 on 2025-10-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0024_alter_userprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id',
            field=models.CharField(default='9c871d8f-d210-4691-89ea-abe6b3333d18', max_length=36, primary_key=True, serialize=False),
        ),
    ]
