# Generated by Django 5.2.7 on 2025-10-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default='e854c4d0-4ff1-4463-8e55-8798b0b36e2b', max_length=36, primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='department',
            table='departments',
        ),
    ]
