# Generated by Django 5.2.7 on 2025-10-02 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0002_alter_department_id_alter_department_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default='5b055276-bcc0-4c86-8f69-ccbf97309b50', max_length=36, primary_key=True, serialize=False),
        ),
    ]
