# Generated by Django 5.2.7 on 2025-10-02 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0003_alter_department_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default='ad2887f7-de84-4709-b7e4-bfdf43ded0dc', max_length=36, primary_key=True, serialize=False),
        ),
    ]
