# Generated by Django 5.2.7 on 2025-10-02 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0004_alter_department_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default='6404a94d-b8b5-4b66-acef-9f9132aae824', max_length=36, primary_key=True, serialize=False),
        ),
    ]
