# Generated by Django 5.2.7 on 2025-10-02 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0005_alter_department_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default='d4bec50b-37db-4653-a2c6-9263ddc09ee3', max_length=36, primary_key=True, serialize=False),
        ),
    ]
