# Generated by Django 5.2.7 on 2025-10-02 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0006_alter_department_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default='7c07df47-6a82-43b1-9653-0bbdc53dccb4', max_length=36, primary_key=True, serialize=False),
        ),
    ]
