# Generated by Django 5.2.7 on 2025-10-02 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0007_alter_department_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default='d802e495-943c-4a88-954f-666e41538bae', max_length=36, primary_key=True, serialize=False),
        ),
    ]
