# Generated by Django 5.2.7 on 2025-10-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0008_alter_department_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default='d06081ee-6ff5-445d-9d2c-4876a241fb4a', max_length=36, primary_key=True, serialize=False),
        ),
    ]
