# Generated by Django 5.2.7 on 2025-10-02 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0009_alter_department_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default='c5ee442b-c345-4cc5-b022-8aaa1cf3e60b', max_length=36, primary_key=True, serialize=False),
        ),
    ]
