# Generated by Django 5.2.7 on 2025-10-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0010_alter_department_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default='37b15b2b-314d-42ed-99d1-6a375c7d0291', max_length=36, primary_key=True, serialize=False),
        ),
    ]
