# Generated by Django 5.2.7 on 2025-10-02 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0011_alter_department_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default='ec45b355-5e52-4763-9b89-48b0dea053b4', max_length=36, primary_key=True, serialize=False),
        ),
    ]
