# Generated by Django 5.2.7 on 2025-10-02 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0013_alter_department_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default='85df6814-9915-4fe4-a79b-78c46456c3a6', max_length=36, primary_key=True, serialize=False),
        ),
    ]
