# Generated by Django 5.2.7 on 2025-10-02 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0014_alter_department_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default='071137d3-41ea-4f3d-8bf7-1238cd24d7cb', max_length=36, primary_key=True, serialize=False),
        ),
    ]
