# Generated by Django 5.2.7 on 2025-10-02 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0015_alter_department_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default='a8143ff6-3fdb-45c7-93ca-810cd3c5e0b7', max_length=36, primary_key=True, serialize=False),
        ),
    ]
