# Generated by Django 5.2.7 on 2025-10-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0016_alter_department_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default='5f2b8794-5851-4be9-b0f1-be260e2f37a8', max_length=36, primary_key=True, serialize=False),
        ),
    ]
