# Generated by Django 5.2.7 on 2025-10-02 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0017_alter_department_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default='098d6f3d-008a-4cf4-acbb-11e624cab05f', max_length=36, primary_key=True, serialize=False),
        ),
    ]
