# Generated by Django 5.2.7 on 2025-10-02 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0018_alter_department_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default='a0ee6ec9-d8df-44ec-9626-8baf17097f37', max_length=36, primary_key=True, serialize=False),
        ),
    ]
