# Generated by Django 5.2.7 on 2025-10-02 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0019_alter_department_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default='8649070e-bcee-4a24-abc1-d79efe513c81', max_length=36, primary_key=True, serialize=False),
        ),
    ]
