# Generated by Django 5.2.7 on 2025-10-02 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0020_alter_department_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default='aa6dd8cd-95e8-4066-8404-4cc0ecfc766d', max_length=36, primary_key=True, serialize=False),
        ),
    ]
