# Generated by Django 5.2.7 on 2025-10-02 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0021_alter_department_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default='bd6885ea-c0a2-4e8f-81f9-f131fff75b42', max_length=36, primary_key=True, serialize=False),
        ),
    ]
