# Generated by Django 5.2.7 on 2025-10-02 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0022_alter_department_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default='b7b42459-482d-4565-89de-f908742fd270', max_length=36, primary_key=True, serialize=False),
        ),
    ]
