# Generated by Django 5.2.7 on 2025-10-02 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0023_alter_department_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default='515136a0-5ca0-4464-ac25-e6e527a562b7', max_length=36, primary_key=True, serialize=False),
        ),
    ]
