# Generated by Django 5.2.7 on 2025-10-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('department', '0024_alter_department_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='id',
            field=models.CharField(default='6b06dec3-1b6a-435c-bd6f-e2199c3ab18a', max_length=36, primary_key=True, serialize=False),
        ),
    ]
